version: '3.4'
services:
  3dplot:
    image: czentye/matplotlib-minimal:3.1.2
    entrypoint: ["python3"]
    command: ["/app/main.py"]
    volumes:
      - ./out:/out
      - ./:/app

  video:
    image: valian/docker-python-opencv-ffmpeg:py3
    entrypoint: ["python3"]
    command: ["/app/video.py"]
    volumes:
      - ./out:/out
      - ./:/app
    